baseURL = "https://ohfix.xyz/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Oh, fixed it"
theme = "hermit"
enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
hasCJKLanguage = true  # If Chinese/Japanese/Korean is your main content language, enable this to make wordCount works right.
rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
googleAnalytics = "UA-125057333-1"

[languages]
  [languages.en]
    weight = 1
    languageName = "en"
    contentDir = "content/en"
    # homeSubtitle = "Fix it"
  [[languages.en.menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10
  [[languages.en.menu.main]]
    name = "Series"
    url = "series/"
    weight = 20
  [[languages.en.menu.main]]
    name = "Categories"
    url = "categories/"
    weight = 30
  [[languages.en.menu.main]]
    name = "About me"
    url = "about-me/"
    weight = 50

  [languages.jp]
    weight = 2
    languageName = "jp"
    contentDir = "content/jp"
    [[languages.jp.menu.main]]
    name = "投稿"
    url = "posts/"
    weight = 10
    [[languages.jp.menu.main]]
      name = "シリーズ"
      url = "series/"
      weight = 20
    [[languages.jp.menu.main]]
      name = "カテゴリー"
      url = "categories/"
      weight = 30
    [[languages.jp.menu.main]]
      name = "私について"
      url = "about-me/"
      weight = 50
  
  [languages.vi]
    weight = 2
    languageName = "vi"
    contentDir = "content/vi"
    [[languages.vi.menu.main]]
    name = "Bài viết"
    url = "posts/"
    weight = 10
    [[languages.vi.menu.main]]
    name = "Loạt"
    url = "series/"
    weight = 20
    [[languages.vi.menu.main]]
    name = "Thể loại"
    url = "categories/"
    weight = 30
  [[languages.vi.menu.main]]
    name = "Về mình"
    url = "about-me/"
    weight = 50

[author]
  name = "Thai Ngo"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]
  dateform        = "January 2, 2006"
  dateformShort   = "January 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  # enableLanguageSwitchingButton = true

  # Metadata mostly used in document's head
  # description = ""
  themeColor = "#494f5c"
  images = ["apple-touch-icon.png"]

  bgImg = "https://wallpapershome.com/images/pages/pic_h/18883.jpg"
  # gitUrl = "https://github.com/ohfix/ohfix-github-io"

  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  # Prefix of link to the git commit detail page. GitInfo must be enabled.

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = true  # Set "text-align: justify" to `.content`.

  relatedPosts = true  # Add a related content section to all single posts page

  # Add custom css
  # customCSS = ["css/foo.css", "css/bar.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/hacbangtam"

  [[params.social]]
    name = "github"
    url = "https://github.com/HBTghost"

  [[params.social]]
    name = "facebook"
    url = "https://facebook.com/hacbangtam"

  [[params.social]]
    name = "email"
    url = "mailto:hacbangtam@gmail.com?subject=Oh, fixed it: "
[outputs]
  home = ["HTML", "RSS", "JSON"]
